Updating with new logic, passing non-parameter access data to mysql command

diff --git a/backup-scripts/sql-backup b/backup-scripts/sql-backup
--- a/backup-scripts/sql-backup
+++ b/backup-scripts/sql-backup
@@ -1,11 +1,18 @@
 #!/bin/bash
-DATE=`date +"%Y-%m-%d"`
-RMDATE=`date +"%Y-%m-%d" -d '-31 day'`
+DATE=`date -I`
+NOWTIME=`date +"%H%M%S"`
+RMDATE=`date -I -d '-31 day'`
 USER=''
 PASS=''
 MYSQLSERVER=''
 DIR=/data/backup/mysql/
 DEST=${DIR}${DATE}
+
+echo "[client]
+user=${USER}
+password=${PASS}
+port=3306
+host=${MYSQLSERVER}" > /usr/local/sbin/.my.cnf
 
 IGNORE="information_schema performance_schema"
 
@@ -13,28 +20,50 @@ if [ ! -d ${DEST} ]
 then
     mkdir -p ${DEST}
 fi
-    DB_LIST=`/usr/bin/mysql -Bse 'show databases' -u ${USER} -p${PASS} -h ${MYSQLSERVER}`
-    for db in $DB_LIST; do
-        skip=0
-        if [ "$IGNORE" != "" ]; then
-            for i in $IGNORE; do
-                [ "$db" == "$i" ] && skip=1 || :
-            done
-        fi
-        if [ "$skip" == "0" ]; then
-        echo $db
-            /usr/bin/mysqldump -u ${USER} -p${PASS} -h ${MYSQLSERVER} --events $db | gzip -c - > ${DEST}/$db.sql.gz
-        fi
-    done
 
+# Single run or all databases
+    if [ $1 ]
+    then
+        check_me=`mysql --defaults-extra-file=/usr/local/sbin/.my.cnf -Bse 'show databases' | grep "$1"`
+        if [ "${check_me}" != "" ]
+        then
+            DB_LIST=${check_me}
+        else
+            echo "Database $1 not found for single backup!"
+            exit 1
+        fi
+    else
+            DB_LIST=`mysql --defaults-extra-file=/usr/local/sbin/.my.cnf -Bse 'show databases'`
+    fi
 
+for db in $DB_LIST; do
+    skip=0
+    if [ "$IGNORE" != "" ]; then
+        for i in $IGNORE; do
+            [ "$db" == "$i" ] && skip=1 || :
+        done
+    fi
+    if [ "$skip" == "0" ]; then
+    # echo "Dumping $db"
+    logger -t sql-backup "Dumping ${db}"
+        if [ -f "${DEST}/$db.sql.gz" ]
+        then
+            mysqldump --defaults-extra-file=/usr/local/sbin/.my.cnf --trigger $db | gzip -c - > ${DEST}/$db-${NOWTIME}.sql.gz
+        else
+            mysqldump --defaults-extra-file=/usr/local/sbin/.my.cnf --trigger $db | gzip -c - > ${DEST}/$db.sql.gz
+        fi
+    fi
+
+done
+
+# Skip removing old backups if single database backup was requested
+if [ $1 ]; then exit; fi
+
+# Remove old backups
 if [[ "`echo ${RMDATE} | awk -F'-' {' print $3 '}`" != "01" ]]
 then
-    if [ -d ${DIR}${RMDATE} ]
+    if [ -d ${DIR}/$RMDATE ]
     then
-        echo "removing ${DIR}${RMDATE}"
-        rm -r ${DIR}${RMDATE}
-    else
-    echo "Nothing to remove at ${RMDATE}"
+        rm -r ${DIR}$RMDATE
     fi
 fi
